name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'

    - name: Set up GOPATH
      run: |
        echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
        echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        go get github.com/pschlump/AesCCM
        go get golang.org/x/crypto/pbkdf2

    - name: Run Unit tests
      run: |
        go test -race -covermode atomic -coverprofile=covprofile ./...
      working-directory: src/github.com/sunshineplan/cipher

    - name: Install goveralls
      run: go get github.com/mattn/goveralls

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
      working-directory: src/github.com/sunshineplan/cipher
