name: Coverage

on:
  workflow_run:
    workflows: [ Test ]
    branches: [ main ]
    types: 
      - completed

jobs:
  coverage:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Send Coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go test -race -covermode atomic -coverprofile=covprofile ./...
          go get github.com/mattn/goveralls
          goveralls -coverprofile=covprofile -service=github
