name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        go get github.com/pschlump/AesCCM
        go get golang.org/x/crypto/pbkdf2

    - name: Run Unit tests
      run: |
        go test -v -race ./...
